### ISSUE TITLE
GraphQL Codegen Type Name Issue

### ISSUE THREAD

**Issue by buffalom** [statamic-rad-pack/runway#279]
### Description

I am using GraphQL Codegen to generate functions and Typescript types based on the GraphQL schema provided by Statamic.

However, the GraphQL types generated by Runway [are not considered valid by Codegen](https://github.com/graphql/graphql-js/blob/da5723860e87c97831c02a1137e9431d96c14239/src/type/assertName.ts#L20).
![image (1)](https://github.com/duncanmcclean/runway/assets/20814747/36a8b1ca-0293-4320-b659-1ed2fad6c62e)

I have currently patched this issue as follows:
[runway-graphql-type-issue.patch](https://github.com/duncanmcclean/runway/files/11565248/runway-graphql-type-issue.patch)

I did not feel very confident about this patch, which is why I have not yet opened a PR. Let me know if I should do so, if you need any further information, or if you think this is more of a Codegen issue.

### Steps to reproduce

Use [nuxt-graphql-client](https://github.com/Diizzayy/nuxt-graphql-client) to fetch data from a Statamic with a Runway resource active. It does not matter, if that resource has GraphQL enabled or not.

### Environment

Environment
Application Name: Sporttag
Laravel Version: 9.52.7
PHP Version: 8.2.3
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: gibb-sporttag-cms.novu.io
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: pusher
Cache: redis
Database: mysql
Logs: single
Mail: log
Queue: sync
Session: redis

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.4.8.2 PRO

Statamic Addons
doublethreedigital/runway: 4.2.10
statamic/eloquent-driver: 1.2.0

**Comment by duncanmcclean** [comment]
Hey! Would you be able to PR your fix and I can get it merged in?

**Comment by duncanmcclean** [comment]
Released in https://github.com/duncanmcclean/runway/releases/tag/v5.0.7

**Comment by Buffalom** [comment]
@duncanmcclean sorry for not opening the PR. I wanted to, but didn't find the time. Either way, thanks a bunch for getting this in.

Btw. Thanks for this awesome package anyway. It rocks 🤟

**Comment by duncanmcclean** [comment]
> @duncanmcclean sorry for not opening the PR. I wanted to, but didn't find the time. Either way, thanks a bunch for getting this in.
> 
> 
> 
> Btw. Thanks for this awesome package anyway. It rocks 🤟

No worries! Have a great rest of your day!
