### ISSUE TITLE
Link Existing button not working for Runway custom resources.

### ISSUE THREAD

**Issue by pdaleramirez** [statamic-rad-pack/runway#410]
### Description

When you go to Blueprints and choose one of your runway's resource blueprints and click on the Link Existing button, it does not open the side window that will allow you to link existing fields or fieldsets. 

There is a javascript error on the dev console; this could be the cause of the UI bug.
![Screenshot 2024-01-24 at 9 17 07 AM](https://github.com/statamic-rad-pack/runway/assets/4172750/a6f75d48-e948-49b0-8bed-6782dbd9b8ed)

### Steps to reproduce

1. Go to Blueprints in Control Panel
2. Click "Link Existing" button

### Environment

I installed the latest version of Statamic and the runway add-on.

**Comment by duncanmcclean** [comment]
This is a bug in Statamic. I've opened a PR to fix it on the Statamic side (https://github.com/statamic/cms/pull/9387). It'll likely be fixed in the next Statamic release.
