### ISSUE TITLE
RunwayRoutes trait throws a "Maximum call stack size" exception

### ISSUE THREAD

**Issue by cworreschk** [statamic-rad-pack/runway#420]
### Description

If a model uses the trait `RunwayRoutes`, an existing (also a not existing) attribute `slug` cannot be accessed without crashing the entire application.

With `PHP 8.2.15` the application simply exits without an error message.

With `PHP 8.3.0` the exception ` Error  Maximum call stack size of 8355840 bytes reached. Infinite recursion?` is displayed.

<img width="653" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/545143/d8ec79a8-ab0e-4db2-986f-56add37bda9d">

### Steps to reproduce

1. Install a fresh new **Statamic** project with the latest version `4.47.0`
2. Install the latest `statamic-rad-pack/runway` package with composer (`6.0.5`)
3. Add the `RunwayRoutes` trait to the existing `User` model
4. Start **Tinker** and instantiate a new user with `$user = new App\Models\User()`
5. Call `$user->slug`

### Environment

**Environment**
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.15 / 8.3.0
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: statamic-runway.test
Maintenance Mode: OFF

**Cache**
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

**Drivers**
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

**Statamic**
Addons: 1
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 Solo

**Statamic Addons**
statamic-rad-pack/runway: 6.0.5

**Comment by duncanmcclean** [comment]
Are you using the `{{ nocache }}` tag anywhere?

**Comment by cworreschk** [comment]
No, I'm not using any `{{ nocache }}` tag.

I'm using Laravel Herd and installed with the `statamic/cli` a fresh new Statamic project. The only installed Addon is `statamic-rad-pack/runway`.

Without configurating anything I've created a new Model with only these lines of code: 
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use StatamicRadPack\Runway\Routing\Traits\RunwayRoutes;
use StatamicRadPack\Runway\Traits\HasRunwayResource;

class Dog extends Model {
    use HasRunwayResource, RunwayRoutes;
}
```

The `runway` configuration has only one resource:
```php
<?php

return [
    'resources' => [
        App\Models\Dog::class => [
            'name'        => 'Dogs',
            'route'       => '/dogs/{{ slug }}',
            'template'    => 'dogs/show',
        ],
    ],
    'disable_migrations' => true,
];

```

I open Tinker straight after that:
<img width="646" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/545143/9f83b52a-bc80-4630-84e3-4aaf54d649b1">

**Comment by cworreschk** [comment]
In my real project I do have a slug `column`, but here in my example with the freshly created Statamic project and the `Dog` class, there is no migration. But in both cases I'm getting the exception.

**Comment by duncanmcclean** [comment]
Do you get the same error when creating models with the `Dog::create([])` syntax?

**Comment by cworreschk** [comment]
If I try to create the `Dog`model with `Dog::create([])` then I get a different error:
![image](https://github.com/statamic-rad-pack/runway/assets/545143/2b35cfc1-21b2-4ed3-ba4c-c5e7368ca520)

I've tested it now with Laravel Sail, to check if Laravel Herd is the problem. But the same exception 😞 

It's really strange. Especially as it's a completely fresh Statamic installation.

**Comment by cworreschk** [comment]
After some tests I found out that the exception only occurs if the `slug` is unset. If it has a value, everything's fine.

In my case the user has the possibility to set the slug manually. If it's not set, in the life cycle event `creating` the value is generated by another field, e.g. `title`.

But the content of the `slug` field cannot be checked, because if it's empty, the exception is thrown.

I have to use this workaround: Get all attributes with `toArray()` or `getAttributes()` and check if the slug is set 🙃

**Comment by duncanmcclean** [comment]
Thanks for doing some digging!

Runway's `RunwayRoutes` trait contains a [`slug()`](https://github.com/statamic-rad-pack/runway/blob/6.x/src/Routing/Traits/RunwayRoutes.php#L30) method (which is required by Statamic's routing contracts).

The `slug` method attempts to get the current slug for the model, using Eloquent's `getAttribute` method. Since, it can't find a value for `slug` on the model, it finds that there's a `slug()` method on the model and tries to use that instead. That's where the infinite loop happens.

We do need the `slug` method in the `RunwayRoutes` method or the feature wouldn't work at all. However, it obviously needs to be re-worked to avoid the infinite loop. I'll have a think about the best way to fix this 🤔
