### ISSUE TITLE
ResourceController::getPrimaryColumn(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by juanjullian** [statamic-rad-pack/runway#422]
### Description

After added the resource, and added some blueprint fields, when i go to the sidebard element (inside "content" sub section) it throws: StatamicRadPack\Runway\Http\Controllers\CP\ResourceController::getPrimaryColumn(): Return value must be of type string, null returned. This happen with both new model and an already existen model, here are: 

 \App\Models\Archivo::class => [
        'name' => 'Archivo',
         'read_only' => true,
         'order_by' => 'inventario',
           'title_field' => 'inventario',
       
         ],
          \App\Register::class => [
        'name' => 'Publicos',
         'read_only' => true,
         'order_by' => 'inventario',
           'title_field' => 'inventario',
       
         ],

### Steps to reproduce

1. Installed runway as docs say.
2. added the resoureces
3. added blueprint fields

### Environment

Environment
Application Name: XXXXXXXX
Laravel Version: 9.52.16
PHP Version: 8.3.2-1+ubuntu20.04.1+deb.sury.org+1
Composer Version: 2.5.8
Environment: local
Debug Mode: OFF
URL: archivolaunion.cl
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: database
Session: file

Statamic
Addons: 2
Antlers: runtime
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.47.0 Solo

Statamic Addons
statamic-rad-pack/runway: 6.0.0
stillat/antlers-layouts: 2.0.0

**Comment by duncanmcclean** [comment]
Can you try updating to Runway v6.0.6?

**Comment by duncanmcclean** [comment]
I also ran into this issue on earlier versions of Runway v6. If you update to the latest version, it should be fixed.

**Comment by juanjullian** [comment]
Sorry for late reply, im gonna rey that versión, but it was misconfiguration, i don't remeber what was exactly, but now i can list the rows of the table's model.
