### ISSUE TITLE
PublishForm overwriting values in nested/stacked context

### ISSUE THREAD

**Issue by caseydwyer** [statamic-rad-pack/runway#426]
### Description

When viewing a stacked relationship (via `belongsTo` fields), something goes haywire after the first layer. I suspect this is happening inside `components/Publish/PublishForm.vue`, in the `prefillBelongsToField` method.

Here's **[a reproduction repo with a simple `City > State > Country` data model](https://github.com/caseydwyer/bug-reproductions/tree/statamic-runway-overwriting-deeply-nested-relationship-values)**. Just make a user and migrate + seed.

### When viewed as a listing, all is well:
![image](https://github.com/statamic-rad-pack/runway/assets/13950848/eb05cdb4-3230-4c88-98ee-55bb7b8d1393)

### And the same goes for viewing the `State`'s publish form directly:
![image](https://github.com/statamic-rad-pack/runway/assets/13950848/1cb646d9-3954-4e10-b6ee-b08a0603a11a)

### But when viewing via stacks, from the `City`, values are overwritten:
![image](https://github.com/statamic-rad-pack/runway/assets/13950848/06f4ab06-fd80-4771-8374-cc12dbd8abc7)
_Overwritten with, I believe, the value from `window.Runway.currentModel.id`). Also note that I fudged some CSS in that screenshot ☝ to show the underlying resource being viewed_

### Steps to reproduce

_(skip 1-3 if using repro-repo linked above)_
1. Set up three models 
2. Set up `Parent` > `Child` > `Grandchild` relationships
3. Seed some data
4. Load the `Child`, see all is well on listing + edit view
5. Load the `Grandchild`, click open the `Child's` belongTo field
6. See buggy behavior with `Grandchild`'s info displayed where `Parent`'s should be

### Environment

<details>
  <summary>Environment</summary>

Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: runway-sandbox.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo

Statamic Addons
statamic-rad-pack/runway: 6.x-dev
</details>

**Comment by duncanmcclean** [comment]
Thanks for the reproduction repository, it's very helpful!

**Comment by caseydwyer** [comment]
No problem, glad to hear that!
