### ISSUE TITLE
Augmentation N+1 query issue on frontend

### ISSUE THREAD

**Issue by mefenlon** [statamic-rad-pack/runway#430]
### Description

On the frontend, runway appears to be ignoring the _with_ relationships during augmentation. The control panel appears to be correct.

Control Panel
<img width="1258" alt="Screenshot 2024-02-13 at 4 16 58 PM" src="https://github.com/statamic-rad-pack/runway/assets/30707325/1a35b9c3-3804-40cc-a391-d118922f04a8">
Frontend
<img width="1270" alt="Screenshot 2024-02-13 at 4 17 11 PM" src="https://github.com/statamic-rad-pack/runway/assets/30707325/35dd1e19-4cdb-4c65-9894-cacf4063f873">

### Steps to reproduce

I have created a repo to demo the issue. Just a very basic set of models, factories and seeders to demo the issue. 
clone https://github.com/mefenlon/statamic-playground.git
composer install
sail up -d
sail artisan migrate:fresh --seed

### Environment

Environment
Application Name: Statamic
Laravel Version: 10.43.0
PHP Version: 8.3.2-1+ubuntu22.04.1+deb.sury.org+1
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: localhost
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 1
Antlers: runtime
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 4.48.0 Solo

Statamic Addons
statamic-rad-pack/runway: 6.1.0

**Comment by duncanmcclean** [comment]
At the moment, only the Control Panel does eager loading automatically. You can manually specify relationships to be eager loaded [using the `with` parameter](https://runway.duncanmcclean.com/templating#content-eager-loading).

For example:

```antlers
{{ runway:product with="categories|tags" }}
```

**Comment by mefenlon** [comment]
Good chance i am doing something wrong, but I am specifying the with and still getting many duplicated queries
```
{{ runway:title sort="sort_title:asc" with='cities' }}
    {{ partial:runway/title/show }}
{{ /runway:title }}
```

**Comment by duncanmcclean** [comment]
Have you tried adding your other relationships to the `with` in the Runway tag? Does that help with performance?

**Comment by duncanmcclean** [comment]
Thanks for the repository, it's very helpful!

**Comment by mefenlon** [comment]
Such an amazing improvement. Started with a few thousand queries and now down to a few hundred after optomizing the with parameters.
