### ISSUE TITLE
Listing models is slow

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/runway#432]
### Description

On our site we have ~1600 Orphans, and a large HasMany relationship too (`OrphanUpdates`).

When we try to list the orphans (locally on my M3 MacBookPro) it takes like 20 secs and I see this:
![CleanShot 2024-02-15 at 16 19 28@2x](https://github.com/statamic-rad-pack/runway/assets/6069653/ebbc4a9a-6248-42e1-b682-b69fd42c08ec)

### Steps to reproduce

1. List Orphans
2. wait
3. wait
4. wait some more

### Environment

Environment
Application Name: Zakat Foundation of America
Laravel Version: 10.44.0
PHP Version: 8.3.2
Composer Version: 2.5.5
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 11
Antlers: runtime
Sites: 3 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.48.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
edalzell/forma: 2.1
jonassiewertsen/statamic-livewire: 2.12.0
statamic-rad-pack/runway: 6.1.0
statamic/seo-pro: 5.4.1
transformstudios/events: 5.3.0
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/neon: dev-fix/upgrade-runway
transformstudios/review: 4.1.4
transformstudios/simple: 4.20.1

**Comment by edalzell** [comment]
@duncanmcclean going to start digging in to this next week

**Comment by edalzell** [comment]
Some details (for myself):

![CleanShot 2024-02-15 at 16 24 05@2x](https://github.com/statamic-rad-pack/runway/assets/6069653/244e2c58-0684-4ff0-bbec-09d80e42270a)

Queries are mostly `select * from `users` where `id` in ('ede02420-f314-41a1-8f53-221518c85893')` and `select * from `users` where 0 = 1`

**Comment by edalzell** [comment]
![CleanShot 2024-02-15 at 16 26 19@2x](https://github.com/statamic-rad-pack/runway/assets/6069653/ba82579a-9ce4-462d-8603-ef41f04a910b)

**Comment by ryanmitchell** [comment]
Are you eager loading users? Can you share your runway resource config and blueprint?

**Comment by ryanmitchell** [comment]
Is it still slow since https://github.com/statamic-rad-pack/runway/pull/435 ?

**Comment by duncanmcclean** [comment]
> Is it still slow since #435 ?

_Probably_. That only really helps when stuff is being augmented, which it isn't in the listing table.

**Comment by edalzell** [comment]
> Is it still slow since #435 ?

Haven't tried yet on the upgraded version. Will try and report back.
