### ISSUE TITLE
Related resource stack doesn't close when saved

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/runway#478]
### Description

If you have a resource with a relationship field, and you open it in the CP, and save, the stack doesn't close, you have to hit `esc`.

Would be great if the stack closed when saved.

### Steps to reproduce

1. have a resource with a relationship to another resource
2. open the relationship resource in the CP, a stack panel opens
3. save the opened resource
4. Note the stack doesn't close

### Environment

Environment
Application Name: Zakat Foundation of America
Laravel Version: 10.48.10
PHP Version: 8.3.6
Composer Version: 2.7.1
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: daily
Mail: smtp
Queue: sync
Session: file

Statamic
Addons: 12
Antlers: runtime
Sites: 3 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.57.3 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.10.0
edalzell/forma: 3.0
jacksleight/statamic-bard-mutator: 2.3.0
jonassiewertsen/statamic-livewire: 2.12.0
statamic-rad-pack/runway: 6.6.5
statamic/seo-pro: 5.4.4
transformstudios/events: 5.4.3
transformstudios/front: 2.0.4
transformstudios/github: dev-main
transformstudios/neon: dev-feature/cf-static-cache
transformstudios/review: 4.1.4
transformstudios/simple: dev-feature/cf-static-cache

**Comment by duncanmcclean** [comment]
I've added the missing 'x' button to the publish form so you can use that to close the publish form.

I haven't made the stack close after saving since that's not something Statamic Core does (yet). Feel free to FR/PR it into Core and we can consider adding it to Runway.
