### ISSUE TITLE
Has Many Field is not loading data in entry

### ISSUE THREAD

**Issue by stepri** [statamic-rad-pack/runway#516]
### Description

I have added an Has Many fieldtype to a blueprint of an entry. When I create an entry, the Has Many field is only showing the title of the field, but no links to Link items, but it does for the Belongs To fieldtype.

![Scherm­afbeelding 2024-06-06 om 15 00 33](https://github.com/statamic-rad-pack/runway/assets/3134589/0812d55e-1ddb-483f-8053-5a98a628a97e)

I did some investigation myself. When I delete those lines, it works: https://github.com/statamic-rad-pack/runway/blob/7.x/src/Fieldtypes/HasManyFieldtype.php#L54-L59

### Steps to reproduce

Create an blueprint for entry with the Has Many fieldtype. Create an entry and it does not show any links for Has Many fieldtype.

### Environment

```bash
Environment
Application Name: Laravel
Laravel Version: 11.9.0
PHP Version: 8.3.7
Composer Version: 2.7.6
Environment: local
Debug Mode: ENABLED
URL: 127.0.0.1:8000
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: redis
Database: mysql
Logs: stack / single, stderr
Mail: log
Queue: database
Session: database

Locales
Installed: ar, bg, bn, cs, da, de, en, es, fa, fi, fr, he, hi, hr, id, it, ja, ko, nl, pl, pt, ro, ru, tr, uk
LaravelLang\Lang\Plugin: 15.5.1
Locales Version: 2.8.0
Protected: en
Publisher Version: 16.4.0

Pulse
Enabled: ENABLED
Version: v1.2.3

Livewire
Livewire: v3.5.0

Statamic
Addons: 4
Sites: 2 (English, Dutch)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.7.1 PRO

Statamic Addons
aryehraber/statamic-logbook: 3.3.0
statamic-rad-pack/runway: 7.2.0
statamic/eloquent-driver: 4.1.0
webographen/statamic-admin-log: 1.1.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: file
Taxonomies: eloquent
Terms: eloquent
Tokens: eloquent
```

**Comment by duncanmcclean** [comment]
Thanks! Should be fixed in the next release, which'll be out in a few minutes.
