### ISSUE TITLE
Delete action of asset not possible when  runway is installed

### ISSUE THREAD

**Issue by freshface** [statamic-rad-pack/runway#530]
### Description

StatamicRadPack\Runway\Actions\Publush & Unpublish gives error when selecting asset.
See video https://cln.sh/WdnQtTCkHsTbBLGlQRj0

### Steps to reproduce

Install runway, select an assets thru the asset browser.

### Environment

Environment
Application Name: GDC Auto
Laravel Version: 10.48.12
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: production
Debug Mode: ENABLED
URL: gdcauto.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: NOT CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Actions\Plugin: 1.8.3
LaravelLang\Attributes\Plugin: 2.10.7
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 13.12.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Livewire
Livewire: v3.5.0

Statamic
Addons: 10
Sites: 1
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.9.0 PRO

Statamic Addons
aerni/social-links: 3.2.0
jacksleight/statamic-bard-texstyle: 3.2.2
jonassiewertsen/statamic-livewire: 3.5.0
ryanmitchell/statamic-translation-manager: 2.0.0
spatie/statamic-responsive-images: 5.0.0
statamic-rad-pack/runway: 7.5.0
studio1902/statamic-peak-browser-appearance: 3.5.0
studio1902/statamic-peak-seo: 8.14.0
studio1902/statamic-peak-tools: 6.1.0
trendyminds/statamic-palette: 1.2.1

**Comment by freshface** [comment]
Is this a valid bug :)

**Comment by edalzell** [comment]
> Is this a valid bug :)

Yup, working on a PR right now as I'm hitting this now as well.
