### ISSUE TITLE
Option values displayed as keys when editing

### ISSUE THREAD

**Issue by mynetx** [statamic-rad-pack/runway#532]
### Description

When there is an Option list in the model's blueprint, the Edit pane will show the option's key instead of the value.

### Steps to reproduce

1. Create a model with some option keys and values.

<img width="868" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/6348321/048c791a-91a0-4530-8bfb-d3c628d94bc7">

2. Add an item, and save.

<img width="373" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/6348321/bf2da5a7-7c49-4e59-a5fa-35db10eec70a">

3. Reload the page.

<img width="332" alt="image" src="https://github.com/statamic-rad-pack/runway/assets/6348321/ea1b8341-2c67-490a-b0d4-c6b584075285">

### Environment

**Environment**
Application Name: Statamic
Laravel Version: 11.11.1
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: **ENABLED**
URL: website.test
Maintenance Mode: OFF
Timezone: UTC
Locale: de

**Cache**
Config: **NOT CACHED**
Events: **NOT CACHED**
Routes: **NOT CACHED**
Views: **CACHED**

**Drivers**
Broadcasting: log
Cache: file
Database: mysql
Logs: **stack** / single
Mail: smtp
Queue: sync
Session: file

**Locales**
Installed: de, en
LaravelLang\Actions\Plugin: 1.8.4
LaravelLang\Attributes\Plugin: 2.10.7
LaravelLang\HttpStatuses\Plugin: 3.8.3
LaravelLang\Lang\Plugin: 15.5.1
Locales Version: 2.9.2
Protected: de, en
Publisher Version: 16.4.0

**Statamic**
Addons: 1
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.11.0 Solo

**Statamic Addons**
statamic-rad-pack/runway: 7.5.1

**Comment by duncanmcclean** [comment]
This is a bug in Statamic Core - you'll see the same behaviour w/ entries or terms.

It might be related to statamic/cms#3179 or statamic/cms#2215.
