### ISSUE TITLE
Revisions status isn't correct

### ISSUE THREAD

**Issue by edalzell** [statamic-rad-pack/runway#551]
### Description

I have a resource where revisions are enabled. There IS a saved version in the db, then I made a small change and clicked Saved Changes.

I see this: 
![CleanShot 2024-07-04 at 17 09 30@2x](https://github.com/statamic-rad-pack/runway/assets/6069653/ec5f34f0-cde3-4349-aabb-dddb063f804c)

I don't believe it should say `This is the published version`. In Statamic collections it has this: 
![CleanShot 2024-07-04 at 17 12 13@2x](https://github.com/statamic-rad-pack/runway/assets/6069653/19b241e6-9c96-4f3c-857f-ac93f134f496)

### Steps to reproduce

1. enable revisions in a resource
2. in an existing model (i.e. not a new one), edit something
3. Click Save changes

### Environment

Environment
Application Name: Zakat Foundation of America
Laravel Version: 11.14.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: zakat.test
Maintenance Mode: OFF
Timezone: America/Los_Angeles
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: file
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Livewire
Livewire: v3.5.2

Statamic
Addons: 13
Sites: 3 (zakat.org (EN), zakat.org (AR), zfinstitute.com (ZFI))
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.12.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.12.0
edalzell/forma: 3.0.1
jacksleight/statamic-bard-mutator: 2.3.1
jacksleight/statamic-distill: 0.7.2
jonassiewertsen/statamic-livewire: 3.6.0
statamic-rad-pack/runway: dev-fix/has-many-revisions
statamic/seo-pro: 6.0.3
transformstudios/events: 5.4.3
transformstudios/front: 3.0.1
transformstudios/github: dev-main
transformstudios/neon: dev-feature/ai-updates
transformstudios/review: 5.0
transformstudios/simple: 5.1.10

**Comment by duncanmcclean** [comment]
Hmm, I can't seem to reproduce this on my end 🤔 

"This is the published version" only shows for me before I make any changes *or* after I hit publish on my changes, the same behaviour as on core. 

https://github.com/statamic-rad-pack/runway/assets/19637309/f5067d8e-89a6-4c1b-8f11-2f9ecd21b086

When I edit a model with no previous revisions, I see "Model has not been published" up until the revision is published.

**Comment by edalzell** [comment]
Make a change, click Save Changes, then reload the page.

**Comment by duncanmcclean** [comment]
Oh, I see it now, thanks!
