### ISSUE TITLE
Cast to camelCase caused issues in StatamicRadPack\Runway\Relationships

### ISSUE THREAD

**Issue by TheBnl** [statamic-rad-pack/runway#569]
### Description

On line [32](https://github.com/statamic-rad-pack/runway/blob/f0ece2b576b90a76a8237cc984cfd7ffb9c8abe5/src/Relationships.php#L32) in Relationships, the method `eloquentRelationships` on `StatamicRadPack\Runway\Resource` casts underscores to camel case so a handle called `my_relation` becomes `myRelation`. However, on all following methods the relation is called directly with the `$field->handle()` see line [44](https://github.com/statamic-rad-pack/runway/blob/f0ece2b576b90a76a8237cc984cfd7ffb9c8abe5/src/Relationships.php#L44) for example.

The issue is that two naming conventions are currently used, so two methods need to be defined on the model for the relationship.
Both `my_relation()` and `myRelation()`. 

Having only `my_relation` defined causes an issue on line 32 and having only `myRelation` defined causes errors on multiple parts of Statamic, it's also used to populate the field values for example.

Omitting the cast to camelCase on line 32 "fixes" the issue.

### Steps to reproduce

Create a HasMany field with a handle using underscores like `my_relation`

**Comment by duncanmcclean** [comment]
Generally, the name of the Has Many field should match the name of the relationship method in your Eloquent model.

If you rename your Has Many field to `myRelation` instead - does it work?

**Comment by TheBnl** [comment]
Unfortunately not, there is an restriction on handles to be written in snake case.

Here is a screenshot with the validation error (in dutch)
<img width="896" alt="Screenshot 2024-07-23 at 16 49 07" src="https://github.com/user-attachments/assets/ec0bc4d2-7d69-45f5-9060-95de65f232a9">

**Comment by duncanmcclean** [comment]
Oh, it's not letting you do it in Statamic, I see. I'll take a look at changing how it works.

In the meantime, renaming the field manually in the YAML file to match the method name on the model should fix it.

**Comment by duncanmcclean** [comment]
I've made some improvements in [v7.7.2](https://github.com/statamic-rad-pack/runway/releases/tag/v7.7.2).

If you're field handle is `my_relation`, Runway will be smart enough to translate that to `myRelation`. You can also use the "Relationship Name" config option on the Has Many fieldtype to explicitly set the relationship that gets used.

**Comment by TheBnl** [comment]
Awesome, thanks for the fix! 🔥
