### ISSUE TITLE
URI Cache won't update when model has parent

### ISSUE THREAD

**Issue by vJoeyz** [statamic-rad-pack/runway#580]
### Description

Table `runway_uris` with uri mappings is not updated when newly created models that extend another class are saved. They **are** saved when they only extend Eloquent's `Model`. So having a custom class as the parent makes the difference here.

### Steps to reproduce

1. Create a modal that extends another class
```php
class Plant extends BaseModel
{
```
```php
class BaseModel extends Model
{
```

2. Create a new instance and save
```php
Plant::create([ 'id' => 1 ]);
```

3. New entries are not saved to runway_uris

### Environment
Application Name: Test
Laravel Version: 11.14.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: local.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 3 (Nederlands, Deutsch, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.12.0 PRO

Statamic Addons
statamic-rad-pack/runway: 7.7.2

**Comment by duncanmcclean** [comment]
What does your custom `BaseModel` class look like? Does it have a `public static function booted()` method by any chance?

**Comment by vJoeyz** [comment]
> What does your custom `BaseModel` class look like? Does it have a `public static function booted()` method by any chance?

Nope, it just has some common methods, nothing special. I'm not sure if it matters, but `Plant` uses mutators.

**Comment by duncanmcclean** [comment]
Hmm, can you share the content of your `BaseModel` class?

**Comment by vJoeyz** [comment]
```php
<?php

namespace App\Models;

use App\Services\Helpers\StringSanitizer;
use Illuminate\Database\Eloquent\Model;

class BaseModel extends Model
{
    protected function sanitizeName(string $name): string
    {
        return StringSanitizer::of($name)
            ->trim()
            ->removeExtraSpaces()
            ->uppercaseWords()
            ->get();
    }
}
```

**Comment by vJoeyz** [comment]
It does seem to work when I run `php please runway:rebuild-uris`

**Comment by vJoeyz** [comment]
Okay I found another thing, it does put one entry in the `runway_uris` table, but keeps overwriting that one record with the latest model I saved (the model_id also isn't correct, it's 11241, not 0):

![image](https://github.com/user-attachments/assets/28b7f70d-03d6-496a-8b84-b75a1cf32c9d)

**Comment by vJoeyz** [comment]
When I remove my own generated ids and instead use auto-incremented ids (using `->id()`) it suddenly works, any idea why?

**Comment by vJoeyz** [comment]
Okay I'm just plain stupid, added `public $incrementing = false;` to my model and now it works, sorry for wasting your time

**Comment by duncanmcclean** [comment]
No worries!
