### ISSUE TITLE
Page variable is null in blade component when using frontend routing

### ISSUE THREAD

**Issue by vJoeyz** [statamic-rad-pack/runway#584]
### Description

~~The `$page` variable is always `null` in templates using blade components when using the [frontend routing](https://runway.duncanmcclean.com/frontend-routing) feature of Runway. However, that page states all variables from the cascade are available.~~

### Steps to reproduce

~~1. Create a resource that uses the `RunwayRoutes` trait
2. Set the template in the Runway config to a template that uses components inside it eg:~~
```php
<x-layout :context="$__data">
    Hello, world!
</x-layout>
```
~~3. Inside the layout component call:~~
```php
@props(['context'])
{{ $page->id }}
```
~~4. Error: `Attempt to read property "id" on null`~~

> Is it perhaps because the resources are not part of the pages collection? What would be the proper way to re-use a layout and still be able to set a page's `<title>`s? Do I have to define a view-only field like title on my resource and save it in the database?

My assumption in the last paragraph was correct, sorry.

I have another question that is somewhat related. Is there a better way to access a resource's fields inside a blade component? Currently, you have to `@aware(['id', 'name', 'description', 'etc..'])` for every single field of a resource.

### Environment

Environment
Application Name: Test
Laravel Version: 11.14.0
PHP Version: 8.3.8
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: local.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 3 (Nederlands, Deutsch, English)
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.12.0 PRO

Statamic Addons
statamic-rad-pack/runway: 7.7.5

**Comment by duncanmcclean** [comment]
I've got a fix ready which will allow you to use the $page variable, like you can with entries, however it depends on a PR in Statamic Core before it can be merged & released.
