### ISSUE TITLE
Removing filters in the CP throws JS Error

### ISSUE THREAD

**Issue by Hysterikon** [statamic-rad-pack/runway#607]
### Description

Added filters cannot be deleted. The removeFieldFilters() method throws a TypeError when clicking the remove (x) button
![runway_filter](https://github.com/user-attachments/assets/c92ce891-4da6-49d2-9d98-9abbc7ff803a)

```js
TypeError: Cannot convert undefined or null to object
    at q.removeFieldFilter (cp-6b42ede9.js:47:70933)
    at click (cp-6b42ede9.js:47:75011)
    at invokeWithErrorHandling (app-acd59ed9.js:5:37633)
    at HTMLButtonElement.I (app-acd59ed9.js:5:14221)
    at j._wrapper (app-acd59ed9.js:5:85432)
```

### Steps to reproduce

1. Create a Runway resource
2. In the CP add a filter for any resource field
3. Press the delete filter button

### Environment

Environment
Application Name: Laravel
Laravel Version: 11.21.0
PHP Version: 8.3.11
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Livewire
Livewire: v3.5.6

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.8.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
statamic-rad-pack/meilisearch: 3.3.0
statamic-rad-pack/runway: 7.9.4
statamic/eloquent-driver: 4.14.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: eloquent
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file

**Comment by duncanmcclean** [comment]
Released as part of [v7.9.5](https://github.com/statamic-rad-pack/runway/releases/tag/v7.9.5).
