### ISSUE TITLE
Filter badges in the CP seem to be broken

### ISSUE THREAD

**Issue by Hysterikon** [statamic-rad-pack/runway#613]
### Description

As mentioned in #607 we had problems with the delete functionality of the filter badges. But it seems that the JavaScript for the badges in general is not working properly.

Some problems I have encountered so far:
- I am unable to create more than one filter, when trying to create a second one the existing one gets deleted.
- Deletion of filters is very delayed, sometimes it takes a few seconds before the badge is removed.
- After creating a new Filter the form is not cleared for a second before it resets

### Steps to reproduce

1. Create a Runway resource
2. Access the CP and view the resource
3. Try to create multiple filters

### Environment

Environment
Application Name: Laravel
Laravel Version: 11.21.0
PHP Version: 8.3.11
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: 
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: database
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: database

Livewire
Livewire: v3.5.6

Sentry
Enabled: MISSING DSN
Environment: local
Laravel SDK Version: 4.8.0
PHP SDK Version: 4.9.0
Release: NOT SET
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 4
Sites: 1
Stache Watcher: Disabled
Static Caching: Disabled
Version: 5.25.0 PRO

Statamic Addons
jonassiewertsen/statamic-livewire: 3.6.0
statamic-rad-pack/meilisearch: 3.3.0
statamic-rad-pack/runway: 7.10.0
statamic/eloquent-driver: 4.14.0

Statamic Eloquent Driver
Asset Containers: eloquent
Assets: eloquent
Blueprints: file
Collection Trees: eloquent
Collections: eloquent
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: eloquent
Navigation Trees: eloquent
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: eloquent
Terms: eloquent
Tokens: file

**Comment by duncanmcclean** [comment]
Apologies this took so long to get fixed. I had a look into it when you reported this but couldn't figure out a fix and I've only just got back to it.
