### ISSUE TITLE
Can't use `url` when indexing Runway models

### ISSUE THREAD

**Issue by aaronbushnell** [statamic-rad-pack/runway#625]
### Description

I'm getting `App\Models\Post::url must return a relationship instance` when trying to index Runway models that use `url` within the fields configuration:

```php
'posts' => [
    'driver' => 'local',
    'searchables' => ['runway:post'],
    'fields' => ['title', 'url'],
],
```

However, `url` does work when including it in a Runway loop:
```antlers
{{ runway:post }}
    {{ url }}
{{ /runway:post }}
```

### Steps to reproduce

1. Create a Laravel model and connect it to Runway (ensuring it has routing setup, too)
2. Setup the example search config above
3. Attempt to update this index using `php please search:update posts`

### Environment

Environment
Application Name: OBFUSCATED
Laravel Version: 11.29.0
PHP Version: 8.3.12
Composer Version: 2.7.7
Environment: local
Debug Mode: ENABLED
URL: post-statamic.test
Maintenance Mode: OFF
Timezone: America/Indiana/Indianapolis
Locale: en

Cache
Config: NOT CACHED
Events: CACHED
Routes: CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: sqlite
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 11
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.33.1 PRO

Statamic Addons
rias/statamic-redirect: 3.8.1
statamic-rad-pack/runway: 7.11.0
statamic/seo-pro: 6.3.0
stillat/relationships: 2.2.1
trendyminds/guide: dev-main
trendyminds/link: dev-main
trendyminds/nerf: 1.2.0
trendyminds/orbit-statamic: 2.0.0
trendyminds/statamic-geocoder: 2.0.2
trendyminds/statamic-palette: 1.2.1
trendyminds/tip: 1.0.0

**Comment by ryanmitchell** [comment]
Can you add the full stack trace?

**Comment by ryanmitchell** [comment]
Sorry for the delay in coming back to you, I missed your reply. Would you be able to make a quick demo repo showing the issue?

**Comment by ryanmitchell** [comment]
Actually never mind, figured it out: https://github.com/statamic-rad-pack/runway/pull/628
