### ISSUE TITLE
Resource-Level Actions Not Working

### ISSUE THREAD

**Issue by caseydwyer** [statamic-rad-pack/runway#637]
### Disclaimer
I'm not familiar with resource-level Actions and don't know how they're _supposed_ to work, so I'm not much help here and I also could be missing something obvious. Just couldn't find any info in Runway or Statamic docs, on this particular type of action. Very possible I'm just wiring this up wrong. Could also be an issue with Statamic, more so than Runway.

### Related PRs
- [Statamic #10471](https://github.com/statamic/cms/pull/10471/)
- [Runway #564](https://github.com/statamic-rad-pack/runway/pull/564/)

### Issue
When running an Action at the resource-level, the Action throws an exception that _sounds_ like it's still expecting selected/specific models to be passed through, which are not available (to my understanding) with resource-level Actions.

### Steps to reproduce

1. Setup a simple model/resource
2. Setup a _really_ simple Action—can just log something in the `run` method
3. Don't restrict Action's visibility, so it's available to the resource itself
4. Attempt to run it from the resource, see error below

![image](https://github.com/user-attachments/assets/c95485d8-f55a-489b-8997-adae8a9f1cc3)

### Environment

<details>
  <summary>Environment</summary>

Environment
Application Name: Statamic
Laravel Version: 11.34.2
PHP Version: 8.2.5
Composer Version: 2.5.4
Environment: local
Debug Mode: ENABLED
URL: runway-sandbox.test
Maintenance Mode: OFF
Timezone: UTC
Locale: en

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: log
Queue: sync
Session: file

Statamic
Addons: 1
Sites: 1
Stache Watcher: Enabled (auto)
Static Caching: Disabled
Version: 5.41.0 Solo

Statamic Addons
statamic-rad-pack/runway: 7.x-dev
</details>

**Comment by duncanmcclean** [comment]
What does your action class look like?

**Comment by duncanmcclean** [comment]
Nevermind, I can see it now. I'll fix it shortly.

**Comment by caseydwyer** [comment]
Yeesh, _crazy_-fast turnaround—thanks so much, Duncan! 🎉
