### ISSUE TITLE
"Belongs To" field now always an array

### ISSUE THREAD

**Issue by Jade-GG** [statamic-rad-pack/runway#640]
### Description

The "Belongs To" field previously had a `max_items:1` on it by default. At some point (that I can't seem to quite pin down), this specific setting stopped getting added to the blueprint on this field and gets silently removed when you save an older blueprint.

This change, in some roundabout way I also can't seem to quite pin down---without caring for [this configuration set here](https://github.com/statamic-rad-pack/runway/blob/7.x/src/Fieldtypes/BelongsToFieldtype.php#L15-L20)---ends up causing the saved value to become an array after the blueprint gets changed by this.

As a result, we've had some pieces of code break that unwittingly assumed it would not be an array. [Here's an example in a public facing repo](https://github.com/rapidez/statamic/pull/92).

Note, I'm currently unsure whether or not this only happens with the eloquent driver.

### Steps to reproduce

1. Add a Belongs To field to your blueprint, or update a blueprint that already has one.
2. Save a value into it
3. Check your data, see it's become an array with 1 value in it

### Environment

Environment
Application Name: [snip]
Laravel Version: 11.31.0
PHP Version: 8.2.20
Composer Version: 2.8.3
Environment: local
Debug Mode: ENABLED
URL: [snip]
Maintenance Mode: OFF
Timezone: Europe/Amsterdam
Locale: nl

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: file
Database: mysql
Logs: stack / single
Mail: smtp
Queue: sync
Session: file

Sentry
Enabled: YES
Environment: local
Laravel SDK Version: 4.9.0
PHP SDK Version: 4.9.0
Release: 51a4715
Sample Rate Errors: 100%
Sample Rate Performance Monitoring: NOT SET
Sample Rate Profiling: NOT SET
Send Default PII: DISABLED

Statamic
Addons: 11
Sites: 7 [snip]
Stache Watcher: Enabled
Static Caching: Disabled
Version: 5.30.0 PRO

Statamic Addons
aryehraber/statamic-captcha: 1.13.0
justbetter/statamic-cache-settings: dev-develop
justbetter/statamic-eloquent-driver-globalset-migration-generator: 0.1.0
justbetter/statamic-environment-permissions: 1.1.0
justbetter/statamic-glide-directive: 2.5.0
justbetter/statamic-image-optimize: 3.1.1
ndx/statamic-bard-color-picker: 2.0.0
pecotamic/sitemap: 1.4.7
ryanmitchell/statamic-translation-manager: 2.0.0
statamic-rad-pack/runway: 7.10.1
statamic/eloquent-driver: 4.15.2

Statamic Eloquent Driver
Asset Containers: file
Assets: eloquent
Blueprints: file
Collection Trees: file
Collections: file
Entries: eloquent
Forms: eloquent
Global Sets: eloquent
Global Variables: file
Navigation Trees: file
Navigations: eloquent
Revisions: eloquent
Sites: file
Taxonomies: file
Terms: eloquent
Tokens: file

**Comment by duncanmcclean** [comment]
When you say "it's now always an array", what do you mean?

Is it saving to the entry as an array? Is it augmenting as an array when it should be a single item?

**Comment by Jade-GG** [comment]
> When you say "it's now always an array", what do you mean?
> 
> Is it saving to the entry as an array? Is it augmenting as an array when it should be a single item?

When I look in the actual saved data in the database, it's saved to the entry as an array, yes.

**Comment by duncanmcclean** [comment]
Gotcha!

It was probably caused by some changes in Statamic 5 - nothing we can't fix.
